user1 = User.create({name: "Peter", age: 30, calorie_limit: 2000})
user2 = User.create({name: "Quagmire", age: 32, calorie_limit: 3000})
user3 = User.create({name: "Jor", age: 31, calorie_limit: 2500})
user4 = User.create({name: "Cleaveland", age: 30, calorie_limit: 2000})
user5 = User.create({name: "Louis", age: 28, calorie_limit: 1800})

meal1 = Meal.create({name: "Cheez Burger", category: "lunch dinner"})
meal2 = Meal.create({name: "Omelette Du Fromage", category: "breakfast"})
meal3 = Meal.create({name: "Steak", category: "lunch dinner"})
meal4 = Meal.create({name: "Pizza", category: "lunch"})

food1 = Food.create({name: "Cheez", calories: 50, protein: 50, fats: 50, carbohydrates: 50, dairy: 1, vegetarian: 1,
  vegan: 0, gluten: 0, halal: 0})
food2 = Food.create({name: "Tomato", calories: 10, protein: 10, fats: 2, carbohydrates: 10, dairy: 0, vegetarian: 1,
  vegan: 1, gluten: 0, halal: 1})
food3 = Food.create({name: "Beef", calories: 100, protein: 100, fats: 100, carbohydrates: 10, dairy: 0, vegetarian: 0,
  vegan: 0, gluten: 0, halal: 0})
food4 = Food.create({name: "Dough", calories: 10, protein: 10, fats: 10, carbohydrates: 80, dairy: 0, vegetarian: 1,
  vegan: 1, gluten: 1, halal: 0})
food5 = Food.create({name: "Chicken", calories: 25, protein: 80, fats: 20, carbohydrates: 80, dairy: 0, vegetarian: 0,
  vegan: 0, gluten: 0, halal: 1})
food6 = Food.create({name: "Egg", calories: 20, protein: 0, fats: 5, carbohydrates: 70, dairy: 0, vegetarian: 1,
  vegan: 1, gluten: 1, halal: 0})

# inventory1 = Inventory.create(user1, food1, 5)
inventory1 = Inventory.create({user: user1, food: food1, quantity: 5})
# inventory2 = Inventory.create(user1, food2, 5)
inventory2 = Inventory.create({user: user1, food: food2, quantity: 5})
# inventory3 = Inventory.create(user1, food3, 5)
inventory3 = Inventory.create({user: user1, food: food3, quantity: 5})
# inventory4 = Inventory.create(user1, food4, 5)
inventory4 = Inventory.create({user: user1, food: food4, quantity: 5})
# inventory5 = Inventory.create(user1, food5, 5)
inventory5 = Inventory.create({user: user1, food: food5, quantity: 5})
# inventory6 = Inventory.create(user1, food6, 5)
inventory6 = Inventory.create({user: user1, food: food6, quantity: 5})
# inventory7 = Inventory.create(user2, food1, 1)
inventory7 = Inventory.create({user: user2, food: food1, quantity: 1})
# inventory8 = Inventory.create(user2, food2, 2)
inventory8 = Inventory.create({user: user2, food: food2, quantity: 2})
# inventory9 = Inventory.create(user2, food3, 3)
inventory9 = Inventory.create({user: user2, food: food3, quantity: 3})
# inventory10 = Inventory.create(user2, food4, 4)
inventory10 = Inventory.create({user: user2, food: food4, quantity: 4})
# inventory11 = Inventory.create(user3, food3, 5)
inventory11 = Inventory.create({user: user3, food: food3, quantity: 5})
# inventory12 = Inventory.create(user3, food4, 4)
inventory12 = Inventory.create({user: user3, food: food4, quantity: 4})
# inventory13 = Inventory.create(user3, food5, 3)
inventory13 = Inventory.create({user: user3, food: food5, quantity: 3})
# inventory14 = Inventory.create(user3, food6, 2)
inventory14 = Inventory.create({user: user3, food: food6, quantity: 2})
# inventory15 = Inventory.create(user4, food1, 20)
inventory15 = Inventory.create({user: user4, food: food1, quantity: 20})
# inventory16 = Inventory.create(user4, food3, 20)
inventory16 = Inventory.create({user: user4, food: food3, quantity: 20})
# inventory17 = Inventory.create(user5, food1, 99)
inventory17 = Inventory.create({user: user5, food: food1, quantity: 99})
# inventory18 = Inventory.create(user5, food2, 99)
inventory18 = Inventory.create({user: user5, food: food2, quantity: 99})
# inventory19 = Inventory.create(user5, food3, 99)
inventory19 = Inventory.create({user: user5, food: food3, quantity: 99})
# inventory20 = Inventory.create(user5, food4, 99)
inventory20 = Inventory.create({user: user5, food: food4, quantity: 99})
# inventory21 = Inventory.create(user5, food5, 99)
inventory21 = Inventory.create({user: user5, food: food5, quantity: 99})
# inventory22 = Inventory.create(user5, food6, 99)
inventory22 = Inventory.create({user: user5, food: food6, quantity: 99})

# ingredient1 = Ingredient.create(meal1, food1, 2)
ingredient1 = Ingredient.create({meal: meal1, food: food2, quantity: 3})
# ingredient2 = Ingredient.create(meal1, food2, 2)
ingredient2 = Ingredient.create({meal: meal1, food: food2, quantity: 2})
# ingredient3 = Ingredient.create(meal1, food3, 1)
ingredient3 = Ingredient.create({meal: meal1, food: food3, quantity: 1})
# ingredient4 = Ingredient.create(meal1, food4, 2)
ingredient4 = Ingredient.create({meal: meal1, food: food4, quantity: 2})
# ingredient5 = Ingredient.create(meal2, food1, 2)
ingredient5 = Ingredient.create({meal: meal2, food: food1, quantity: 2})
# ingredient6 = Ingredient.create(meal2, food6, 2)
ingredient6 = Ingredient.create({meal: meal2, food: food6, quantity: 2})
# ingredient7 = Ingredient.create(meal3, food3, 1)
ingredient7 = Ingredient.create({meal: meal3, food: food3, quantity: 1})
# ingredient8 = Ingredient.create(meal4, food1, 5)
ingredient8 = Ingredient.create({meal: meal4, food: food1, quantity: 5})
# ingredient9 = Ingredient.create(meal4, food2, 3)
ingredient9 = Ingredient.create({meal: meal4, food: food2, quantity: 3})
# ingredient10 = Ingredient.create(meal4, food4, 2)
ingredient10 = Ingredient.create({meal: meal4, food: food4, quantity: 2})

# favorite1 = Favorite.create(user1, meal1)
favorite1 = Favorite.create({user: user1, meal: meal1})
# favorite2 = Favorite.create(user1, meal2)
favorite2 = Favorite.create({user: user1, meal: meal3})
# favorite3 = Favorite.create(user1, meal3)
favorite3 = Favorite.create({user: user1, meal: meal3})
# favorite4 = Favorite.create(user1, meal4)
favorite4 = Favorite.create({user: user1, meal: meal4})
# favorite5 = Favorite.create(user2, meal1)
favorite5 = Favorite.create({user: user2, meal: meal1})
# favorite6 = Favorite.create(user2, meal3)
favorite6 = Favorite.create({user: user2, meal: meal3})
# favorite7 = Favorite.create(user3, meal2)
favorite7 = Favorite.create({user: user3, meal: meal2})
# favorite8 = Favorite.create(user3, meal3)
favorite8 = Favorite.create({user: user3, meal: meal3})
# favorite9 = Favorite.create(user4, meal1)
favorite9 = Favorite.create({user: user4, meal: meal1})
# favorite10 = Favorite.create(user5, meal1)
favorite10 = Favorite.create({user: user5, meal: meal1})
# favorite11 = Favorite.create(user5, meal4)
favorite11 = Favorite.create({user: user5, meal: meal4})
