user1 = User.new
user1.name = "Peter"
user1.age = 30
user2.calorie_limit = 2000
user2 = User.new
user2.name = "Quagmire"
user2.age = 32
user2.calorie_limit = 3000
user3 = User.new
user3.name = "Joe"
user3.age = 31
user3.calorie_limit = 2500
user4 = User.new
user4.name = "Cleaveland"
user4.age = 30
user4.calorie_limit = 2000
user5 = User.new
user5.name = "Louis"
user5.age = 28
user5.calorie_limit = 1800
meal1 = Meal.new
meal1.name = "Cheez Burger"
meal1.category = "lunch dinner"
meal2 = Meal.new
meal2.name = "Omelette Du Fromage"
meal2.category = "breakfast"
meal3 = Meal.new
meal3.name = "Steak"
meal3.category = "lunch dinner"
meal4 = Meal.new
meal4.name = "Pizza"
meal4.category = "lunch"
food1 = Food.create
food1.name = "Cheez"
food1.calories = 50
food1.protein = 50
food1.fats = 50
food1.carbohydrates = 50
food1.dairy = True
food1.vegetarian = True
food1.vegan = False
food1.contains_gluten = False
food1.halal = False
food2 = Food.create
food2.name = "Tomato"
food2.calories = 10
food2.protein = 10
food2.fats = 2
food2.carbohydrates = 10
food2.dairy = False
food2.vegetarian = True
food2.vegan = True
food2.contains_gluten = False
food2.halal = True
food3 = Food.create
food3.name = "Beef"
food3.calories = 100
food3.protein = 100
food3.fats = 100
food3.carbohydrates = 10
food3.dairy = False
food3.vegetarian = False
food3.vegan = False
food3.contains_gluten = False
food3.halal = False
food4 = Food.create
food4.name = "Dough"
food4.calories = 10
food4.protein = 10
food4.fats = 10
food4.carbohydrates = 80
food4.dairy = False
food4.vegetarian = True
food4.vegan = True
food4.contains_gluten = True
food4.halal = False
food5 = Food.create
food5.name = "Chicken"
food5.calories = 25
food5.protein = 80
food5.fats = 20
food5.carbohydrates = 80
food5.dairy = False
food5.vegetarian = False
food5.vegan = False
food5.contains_gluten = False
food5.halal = True
food6 = Food.create
food6.name = "Egg"
food6.calories = 20
food6.protein = 0
food6.fats = 5
food6.carbohydrates = 70
food6.dairy = False
food6.vegetarian = True
food6.vegan = True
food6.contains_gluten = True
food6.halal = False
inventory1 = Inventory.new(user1, food1, 5)
inventory2 = Inventory.new(user1, food2, 5)
inventory3 = Inventory.new(user1, food3, 5)
inventory4 = Inventory.new(user1, food4, 5)
inventory5 = Inventory.new(user1, food5, 5)
inventory6 = Inventory.new(user1, food6, 5)
inventory7 = Inventory.new(user2, food1, 1)
inventory8 = Inventory.new(user2, food2, 2)
inventory9 = Inventory.new(user2, food3, 3)
inventory10 = Inventory.new(user2, food4, 4)
inventory11 = Inventory.new(user3, food3, 5)
inventory12 = Inventory.new(user3, food4, 4)
inventory13 = Inventory.new(user3, food5, 3)
inventory14 = Inventory.new(user3, food6, 2)
inventory15 = Inventory.new(user4, food1, 20)
inventory16 = Inventory.new(user4, food3, 20)
inventory17 = Inventory.new(user5, food1, 99)
inventory18 = Inventory.new(user5, food2, 99)
inventory19 = Inventory.new(user5, food3, 99)
inventory20 = Inventory.new(user5, food4, 99)
inventory21 = Inventory.new(user5, food5, 99)
inventory22 = Inventory.new(user5, food6, 99)
ingredient1 = Ingredients.new(meal1, food1, 2)
ingredient2 = Ingredients.new(meal1, food2, 2)
ingredient3 = Ingredients.new(meal1, food3, 1)
ingredient4 = Ingredients.new(meal1, food4, 2)
ingredient5 = Ingredients.new(meal2, food1, 2)
ingredient6 = Ingredients.new(meal2, food6, 2)
ingredient7 = Ingredient.new(meal3, food3, 1)
ingredient8 = Ingredients.new(meal4, food1, 5)
ingredient9 = Ingredients.new(meal4, food2, 3)
ingredient10 = Ingredient.new(meal4, food4, 2)
favorites1 = Favorite.new(user1, meal1)
favorites2 = Favorite.new(user1, meal2)
favorites3 = Favorite.new(user1, meal3)
favorites4 = Favorite.new(user1, meal4)
favorites5 = Favorite.new(user2, meal1)
favorites6 = Favorite.new(user2, meal3)
favorites7 = Favorite.new(user3, meal2)
favorites8 = Favorite.new(user3, meal3)
favorites9 = Favorite.new(user4, meal1)
favorites10 = Favorite.new(user5, meal1)
favorites11 = Favorite.new(user5, meal4)
